-- GENERATED by tools/generate_mod_wiring.js from tools/snow_assets.json.
-- Edit the spec, not this file.

local Profiles = {}

-- Every stage leaves worldModel nil on purpose. Firearms must fall through to
-- the engine's HandWeapon handling, which keeps a dropped weapon flat and still
-- textured; a WorldStaticModel forces the generic atlas branch and stands it
-- upright.
local profiles = {
    {
        fullType = "Base.AssaultRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_AssaultRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_AssaultRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_AssaultRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_AssaultRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.AssaultRifle2",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_M14_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_M14_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_M14_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_M14_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.HuntingRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_HuntingRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_HuntingRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_HuntingRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_HuntingRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.JS14_Rifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_JS14_Rifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_JS14_Rifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_JS14_Rifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_JS14_Rifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.L92_Carbine",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_L92_Carbine_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_L92_Carbine_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_L92_Carbine_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_L92_Carbine_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.MSR7T_Rifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_MSR7T_Rifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_MSR7T_Rifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_MSR7T_Rifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_MSR7T_Rifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.TrapperCarbine",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Trapper_Carbine_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Trapper_Carbine_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Trapper_Carbine_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Trapper_Carbine_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.VarmintRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_VarmintRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_VarmintRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_VarmintRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_VarmintRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
}

Profiles.byFullType = {}
for _, profile in ipairs(profiles) do
    Profiles.byFullType[profile.fullType] = profile
end

-- Future aliases must be explicitly keyed by FullType. A shared WeaponSprite
-- never enables an unrelated item.
Profiles.aliasesByFullType = {}

function Profiles.find(item)
    if not item then return nil end
    local fullType = item:getFullType()
    local profile = Profiles.byFullType[fullType]
    if not profile then
        local canonicalType = Profiles.aliasesByFullType[fullType]
        profile = canonicalType and Profiles.byFullType[canonicalType] or nil
    end
    return profile and profile.enabled and profile or nil
end

return Profiles
