-- GENERATED by tools/generate_mod_wiring.js from tools/snow_assets.json.
-- Edit the spec, not this file.

local Profiles = {}

-- Every stage leaves worldModel nil on purpose. Firearms must fall through to
-- the engine's HandWeapon handling, which keeps a dropped weapon flat and still
-- textured; a WorldStaticModel forces the generic atlas branch and stands it
-- upright.
local profiles = {
    {
        fullType = "Base.AssaultRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_AssaultRifle_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_AssaultRifle_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_AssaultRifle_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_AssaultRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_AssaultRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_AssaultRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_AssaultRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.AssaultRifle2",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_M14_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_M14_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_M14_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_M14_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_M14_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_M14_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_M14_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.DoubleBarrelShotgun",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_DoubleBarrelShotgun_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_DoubleBarrelShotgun_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_DoubleBarrelShotgun_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_DoubleBarrelShotgun_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_DoubleBarrelShotgun_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_DoubleBarrelShotgun_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_DoubleBarrelShotgun_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.DoubleBarrelShotgunSawnoff",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_ShotgunDoubleBarrelSawn_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.HuntingRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_HuntingRifle_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_HuntingRifle_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_HuntingRifle_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_HuntingRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_HuntingRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_HuntingRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_HuntingRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.JS14_Rifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_JS14_Rifle_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_JS14_Rifle_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_JS14_Rifle_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_JS14_Rifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_JS14_Rifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_JS14_Rifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_JS14_Rifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.JS3T_Shotgun",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_JS3T_Shotgun_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_JS3T_Shotgun_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_JS3T_Shotgun_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_JS3T_Shotgun_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_JS3T_Shotgun_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_JS3T_Shotgun_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_JS3T_Shotgun_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.L92_Carbine",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_L92_Carbine_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_L92_Carbine_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_L92_Carbine_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_L92_Carbine_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_L92_Carbine_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_L92_Carbine_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_L92_Carbine_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.MSR7T_Rifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_MSR7T_Rifle_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_MSR7T_Rifle_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_MSR7T_Rifle_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_MSR7T_Rifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_MSR7T_Rifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_MSR7T_Rifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_MSR7T_Rifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Pistol",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Handgun03_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Handgun03_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Handgun03_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Handgun03_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Handgun03_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Handgun03_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Handgun03_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Pistol2",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Handgun02_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Handgun02_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Handgun02_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Handgun02_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Handgun02_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Handgun02_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Handgun02_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Pistol3",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Handgun_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Handgun_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Handgun_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Handgun_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Handgun_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Handgun_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Handgun_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Revolver",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Revolver_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Revolver_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Revolver_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Revolver_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Revolver_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Revolver_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Revolver_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Revolver_Long",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Revolver_Long_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Revolver_Long_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Revolver_Long_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Revolver_Long_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Revolver_Long_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Revolver_Long_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Revolver_Long_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Revolver_Short",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Revolver_Short_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Revolver_Short_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Revolver_Short_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Revolver_Short_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Revolver_Short_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Revolver_Short_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Revolver_Short_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.Shotgun",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Shotgun_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Shotgun_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Shotgun_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Shotgun_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Shotgun_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Shotgun_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Shotgun_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.ShotgunSawnoff",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_ShotgunSawnOff_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_ShotgunSawnOff_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_ShotgunSawnOff_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_ShotgunSawnOff_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_ShotgunSawnOff_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_ShotgunSawnOff_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_ShotgunSawnOff_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.TrapperCarbine",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_Trapper_Carbine_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_Trapper_Carbine_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_Trapper_Carbine_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_Trapper_Carbine_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_Trapper_Carbine_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_Trapper_Carbine_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_Trapper_Carbine_SnowFull", worldModel = nil, icon = nil },
        },
    },
    {
        fullType = "Base.VarmintRifle",
        enabled = true,
        stages = {
            [0] = { equippedModel = nil, worldModel = nil, icon = nil },
            [-3] = { equippedModel = "EW_VarmintRifle_WetHeavy", worldModel = nil, icon = nil },
            [-2] = { equippedModel = "EW_VarmintRifle_WetMedium", worldModel = nil, icon = nil },
            [-1] = { equippedModel = "EW_VarmintRifle_WetLight", worldModel = nil, icon = nil },
            [1] = { equippedModel = "EW_VarmintRifle_SnowLight", worldModel = nil, icon = nil },
            [2] = { equippedModel = "EW_VarmintRifle_SnowMedium", worldModel = nil, icon = nil },
            [3] = { equippedModel = "EW_VarmintRifle_SnowHeavy", worldModel = nil, icon = nil },
            [4] = { equippedModel = "EW_VarmintRifle_SnowFull", worldModel = nil, icon = nil },
        },
    },
}

Profiles.byFullType = {}
for _, profile in ipairs(profiles) do
    Profiles.byFullType[profile.fullType] = profile
end

-- Future aliases must be explicitly keyed by FullType. A shared WeaponSprite
-- never enables an unrelated item.
Profiles.aliasesByFullType = {}

function Profiles.find(item)
    if not item then return nil end
    local fullType = item:getFullType()
    local profile = Profiles.byFullType[fullType]
    if not profile then
        local canonicalType = Profiles.aliasesByFullType[fullType]
        profile = canonicalType and Profiles.byFullType[canonicalType] or nil
    end
    return profile and profile.enabled and profile or nil
end

return Profiles
